### ISSUE TITLE
Успешно улучшено (нет:)

### ISSUE THREAD

**Issue by ghost** [Newmcpe/fuflomuskempire#1]
Пытается купить улучшение которое на самом деле недоступно, что бы его улучшить нужно пригласить +1 друга, а бот пытается его постоянно улучшить

[Offline Bonus Claimer] account-1  |  Успешно собрано оффлайн бонусов +(294353 🪙)
[Upgrader] account-1  |  Успешно улучшено secretary с ценой 8600 до 3 уровня |
 Заработок каждый час: 5 146 250 (+900)
 Осталось денег: 5 372 844
[Upgrader] account-1  |  Успешно улучшено secretary с ценой 8600 до 3 уровня |
 Заработок каждый час: 5 146 250 (+900)
 Осталось денег: 5 372 844
[Upgrader] account-1  |  Успешно улучшено secretary с ценой 8600 до 3 уровня |
 Заработок каждый час: 5 146 250 (+900)
 Осталось денег: 5 372 844
[Upgrader] account-1  |  Успешно улучшено secretary с ценой 8600 до 3 уровня |
 Заработок каждый час: 5 146 250 (+900)
 Осталось денег: 5 372 844
[Upgrader] account-1  |  Успешно улучшено secretary с ценой 8600 до 3 уровня |
 Заработок каждый час: 5 146 250 (+900)
 Осталось денег: 5 372 844
[Upgrader] account-1  |  Успешно улучшено secretary с ценой 8600 до 3 уровня |
 Заработок каждый час: 5 146 250 (+900)
 Осталось денег: 5 372 844

**Comment by Newmcpe** [comment]
Исправлено в https://github.com/Newmcpe/fuflomuskempire/commit/c11a7c61b95c00b1582d9fc610b70b8b00f5d348

**Comment by ghost** [comment]
Теперь бот пытается купить улучшение, которое требует более высокий уровень другого, а то в свою очередь  прокачать нельзя, т.к. нужно пригласить +1 друга)

[Upgrader] account-1  |  Успешно улучшено computers с ценой 18500 до 5 уровня |
 Заработок каждый час: 10 070 550 (+1500)
 Осталось денег: 17 726 562
[Upgrader] account-3  |  Успешно улучшено computers с ценой 18500 до 5 уровня |
 Заработок каждый час: 10 475 550 (+1500)
 Осталось денег: 18 343 299
[Upgrader] account-2  |  Успешно улучшено chairs с ценой 14350000 до 20 уровня |
 Заработок каждый час: 19 532 200 (+570000)
 Осталось денег: 8 793 735
[Upgrader] account-1  |  Успешно улучшено computers с ценой 18500 до 5 уровня |
 Заработок каждый час: 10 070 550 (+1500)
 Осталось денег: 17 726 562
[Upgrader] account-3  |  Успешно улучшено computers с ценой 18500 до 5 уровня |
 Заработок каждый час: 10 475 550 (+1500)
 Осталось денег: 18 343 299
[Upgrader] account-2  |  Успешно улучшено chairs с ценой 14350000 до 20 уровня |
 Заработок каждый час: 19 532 200 (+570000)
 Осталось денег: 8 793 735
[Upgrader] account-1  |  Успешно улучшено computers с ценой 18500 до 5 уровня |
 Заработок каждый час: 10 070 550 (+1500)
 Осталось денег: 17 726 562
[Upgrader] account-3  |  Успешно улучшено computers с ценой 18500 до 5 уровня |
 Заработок каждый час: 10 475 550 (+1500)
 Осталось денег: 18 343 299
 
Вот например, account-1 и account-3, бот пытается купить улучшение Компьютеры, но оно требует Рабочие места ур.5, а чтобы прокачать Рабочие места ур.5 нужно +1 друг. Со стульями на account-2 аналогично. И так гоняет прокачку по кругу.
upd. на акках есть $ и можно купить другие улучшения. Скриншот: https://i.imgur.com/sHVuyGR.jpeg

**Comment by Newmcpe** [comment]
@MaddFun запушила исправление, попробуй сейчас

**Comment by ghost** [comment]
Ага, теперь всё нормально с улучшениями, покупает те которые доступны, спасибо.

**Comment by ghost** [comment]
Что-то опять сломалось с последним обновлением.
https://i.imgur.com/LOym21c.png
