### ISSUE TITLE
error

### ISSUE THREAD

**Issue by oboroccv** [Newmcpe/fuflomuskempire#10]
![1](https://github.com/user-attachments/assets/8eb8e603-90e7-4d3b-9a68-566bce8c2a1a)

**Comment by mainiken** [comment]
Да такая же проблема.
После чего в игре появляется  ошибка и игра больше не запускается. возможно бан.
![image](https://github.com/user-attachments/assets/b8f95cda-c978-46ab-9674-ea23e576b56c)

**Comment by mainiken** [comment]
Мне ответили разработчики игры, если у вас такая же ошибка как и у меня - ваш аккаунт получил бан.
Спасибо за скрипт.

**Comment by ghost** [comment]
Да уж, спасибо за скрипт, аналогичная ошибка auth) единственный бот из 30 из-за которого заблокировали) хпхппхпхпхпхпх

**Comment by Newmcpe** [comment]
Мне тоже прилетел бан, интересная игрушка

**Comment by Newmcpe** [comment]
401 на неЗабаненных аккаунтах пофикшена в https://github.com/Newmcpe/fuflomuskempire/commit/da4c01e8e9e12a126ca7737fa8fbe765649d486f
