### ISSUE TITLE
upgrader

### ISSUE THREAD

**Issue by supmyhava** [Newmcpe/fuflomuskempire#15]
why the bot is always but just the task_manager and not more that that ? like cars to make the profit per hour higher ?

[Upgrader] 11  |  Недостаточно денег для улучшения task_manager Не хватает: 2,075,359 🪙 | Расчетное время до наличия денег: 2.88 часов
[Offline Bonus Claimer] 11  |  Собран оффлайн доход +601 🪙
[Tapper] 11  |  Натапал на +2,610 🪙  |  Осталось энергии: 7890
[Offline Bonus Claimer] 11  |  Собран оффлайн доход +8,622 🪙
[Tapper] 11  |  Натапал на +2,610 🪙  |  Осталось энергии: 7890
[Tapper] 11  |  Натапал на +1,200 🪙  |  Осталось энергии: 9300
[Offline Bonus Claimer] 11  |  Собран оффлайн доход +4,411 🪙
[Tapper] 11  |  Натапал на +1,500 🪙  |  Осталось энергии: 9000
[Tapper] 11  |  Натапал на +1,440 🪙  |  Осталось энергии: 9060
[Offline Bonus Claimer] 11  |  Собран оффлайн доход +6,416 🪙
[Tapper] 11  |  Натапал на +2,025 🪙  |  Осталось энергии: 8475
[Tapper] 11  |  Натапал на +1,320 🪙  |  Осталось энергии: 9180
[Tapper] 11  |  Натапал на +2,520 🪙  |  Осталось энергии: 7980
[Offline Bonus Claimer] 11  |  Собран оффлайн доход +2,606 🪙
[Tapper] 11  |  Натапал на +1,260 🪙  |  Осталось энергии: 9240
[Tapper] 11  |  Натапал на +1,575 🪙  |  Осталось энергии: 8925
[Offline Bonus Claimer] 11  |  Собран оффлайн доход +8,221 🪙
[Tapper] 11  |  Натапал на +2,340 🪙  |  Осталось энергии: 8160

**Comment by Newmcpe** [comment]
already fixed
