### ISSUE TITLE
New language support: English

### ISSUE THREAD

**Issue by lucasnguyen3979** [Newmcpe/fuflomuskempire#2]
Can you please use English language for the messages in the bot and README?

**Comment by Newmcpe** [comment]
Ok, i'll add this in near future (1-3 days)

**Comment by Newmcpe** [comment]
Added [README ](https://github.com/Newmcpe/fuflomuskempire/blob/master/README.en.md )in English language

**Comment by lucasnguyen3979** [comment]
String messages in the bot still need to be converted to English, for example as shown:

![image](https://github.com/user-attachments/assets/9be5840b-f216-45da-8fb8-7b979147845b)

Btw, can you switch to using NPM instead of pNPM to make it lighter?

**Comment by Newmcpe** [comment]
You can itself change package manager, i like to use only pnpm. Maybe you'd like to do a pull request with multilingualism, because I'm focusing on slightly different functions right now?

**Comment by Newmcpe** [comment]
> String messages in the bot still need to be converted to English, for example as shown:
> 
> ![image](https://private-user-images.githubusercontent.com/25925555/351403146-9be5840b-f216-45da-8fb8-7b979147845b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTIzNjcsIm5iZiI6MTcyMTc1MjA2NywicGF0aCI6Ii8yNTkyNTU1NS8zNTE0MDMxNDYtOWJlNTg0MGItZjIxNi00NWRhLThmYjgtN2I5NzkxNDc4NDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE2Mjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZDRmNDA1NWU1ZmJjNTUxYjY0YTEzYjI3NmZiZGU2MzA2ZGVjNzc2NzZkNzY0YjgyNjU4NmVjYTZkZTEzNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.825F6MFFiO_oMq3xhAFuIvx5joNF5fDzxzpu7S4Buyo)
> 
> Btw, can you switch to using NPM instead of pNPM to make it lighter?

![image](https://github.com/user-attachments/assets/522f5682-36ec-44fa-b007-8e69be04c7e1)

**Comment by lucasnguyen3979** [comment]
@Newmcpe do you want to change everything to English? Or if you want multilingual, please install the necessary libraries you want and I will translate to English.
