### ISSUE TITLE
Как отключить PVP?

### ISSUE THREAD

**Issue by Igaresha69** [Newmcpe/fuflomuskempire#3]
Привет, в первую очередь хочу сказать огромное спасибо за бота) Это, пожалуй, самый продуманный и идеально реализованный бот для тг игрушки, лучше я не видел.
Напрягает такое количество баттлов, понимаю что за сутки он набьет их пару сотен, а возможно даже и тысячу на каждом аккаунте. Возможно ли как-то выставить задержку между баттлами? В конфиге вроде вижу эту настройку, но там значение из кучи цифр, не понимаю)

**Comment by Igaresha69** [comment]
Я бы хотел попробовать настроить так, чтобы бот каждые 2-3 часа заходил собирать оффлайн монетки, прокачивался и дальше засыпал на свои 2-3 часа. Если это возможно как-то настроить, был бы признателен за подсказку где и как :)

**Comment by ghost** [comment]
Конфига как такого нет вроде, правь в самих файлах

Например для батлов, файл dist\modules\combater.js
if (money **< 25000**)
Если денег < 25000, то бот не играет батл, можно поменять на money > 25000, тогда бот совсем не будет играть, если денег больше 25000

Количества батлов нет, есть лузстрик, череда поражений, можно поставить своё значение
if (loseStreak **>= 4**)

Если их 4 подряд, то бот засыпает на 30 сек, можно поставить своё значение
setCooldown('noPvpUntil', account, **30**)

Оффлайн бонус забирает каждые 60 сек
В файле dist\modules\offline-bonus-claimer.js можно поставить своё значение
setCooldown('noOfflineBonusUntil', account, **60**)

**Comment by Newmcpe** [comment]
Добавлено в коммите https://github.com/Newmcpe/fuflomuskempire/commit/9cf9b295647668200aac4425d31c1799ccae4d30
