### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'currentLevel')

### ISSUE THREAD

**Issue by Domenick90** [Newmcpe/fuflomuskempire#4]
[Offline Bonus Claimer] Domenick  |  Успешно собрано оффлайн бонусов (+5584 🪙)
TypeError: Cannot read properties of undefined (reading 'currentLevel')
    at file:///home/osboxes/fuflomuskempire/dist/modules/upgrader.js:22:21
    at Array.every (<anonymous>)
    at file:///home/osboxes/fuflomuskempire/dist/modules/upgrader.js:21:60
    at Array.filter (<anonymous>)
    at upgrader (file:///home/osboxes/fuflomuskempire/dist/modules/upgrader.js:14:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async accountHeartbeat (file:///home/osboxes/fuflomuskempire/dist/modules/heartbeat.js:18:9)
    at async startHeartbeat (file:///home/osboxes/fuflomuskempire/dist/modules/heartbeat.js:12:9)
    at async file:///home/osboxes/fuflomuskempire/dist/index.js:43:9 {
  id: 'recruiter',
  isActive: true,
  currentLevel: 1,
  profitCurrent: 250,
  levels: [
    {
      level: 1,
      title: '',
      requiredSkills: [Object],
      requiredHeroLevel: 2,
      requiredFriends: 0,
      desc: ''
    },
    {
      level: 3,
      title: '',
      requiredSkills: [Object],
      requiredHeroLevel: 0,
      requiredFriends: 0,
      desc: ''
    },
    {
      level: 5,
      title: '',
      requiredSkills: [Object],
      requiredHeroLevel: 0,
      requiredFriends: 0,
      desc: ''
    },
    {
      level: 221,
      title: '',
      requiredSkills: [Object],
      requiredHeroLevel: 21,
      requiredFriends: 0,
      desc: ''
    },
    {
      level: 231,
      title: '',
      requiredSkills: [Object],
      requiredHeroLevel: 22,
      requiredFriends: 0,
      desc: ''
    }
  ],
  profitNextLevel: 500,
  priceNextLevel: 10000,
  profitIncrement: 250
}
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Newmcpe** [comment]
Обновитесь до последней версии бота
