### ISSUE TITLE
зациклены обновления карточек

### ISSUE THREAD

**Issue by unkby** [Newmcpe/fuflomuskempire#7]
Выполняет апгрейд одной и той же карточки, пишет сумму, уровень.
Но баланс не меняется и это зацикливается

На всех аккаунтах

**Comment by unkby** [comment]
![2024-07-24_22-13-34](https://github.com/user-attachments/assets/e0937b3e-6e58-40cd-9890-c924a270a08b)

**Comment by Newmcpe** [comment]
А есть возможность посмотреть, что пишет в инфе об этих карточках в самом приложении?

**Comment by unkby** [comment]
карточку футбол обновить нельзя, не хватает друзей. нужно еще 2 друга
![photo_2024-07-24_22-35-58](https://github.com/user-attachments/assets/538a63f8-ddba-4069-8c24-d64940b8cf97)

и секретаря тоже не могу - нужен друг

видимо не определяет условия покупки

**Comment by Newmcpe** [comment]
> карточку футбол обновить нельзя, не хватает друзей. нужно еще 2 друга ![photo_2024-07-24_22-35-58](https://private-user-images.githubusercontent.com/152211435/351854082-538a63f8-ddba-4069-8c24-d64940b8cf97.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NTU3NDMsIm5iZiI6MTcyMTg1NTQ0MywicGF0aCI6Ii8xNTIyMTE0MzUvMzUxODU0MDgyLTUzOGE2M2Y4LWRkYmEtNDA2OS04YzI0LWQ2NDk0MGI4Y2Y5Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQyMTEwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2NlNDQ3NWIwMTEzNWRjMWNhMDg5OGQyMTgwMjA4MjBlNjExMTEyYzYyY2RkNzlhZjZmNGY1NWEzOWEzMDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ly9lpQx4RiSEhDOP1TYqsoZEl9M2AxNN4mE_gPDJ_bs)
> 
> и секретаря тоже не могу - нужен друг
> 
> видимо не определяет условия покупки

попробовала имплементировать логику из оригинального кода приложения в коммите https://github.com/Newmcpe/fuflomuskempire/commit/eb28fac9fddd7f24853b18bed537fd1aef7feee3, попробуй обновиться и отписаться по результату

**Comment by unkby** [comment]
заработало
Спасибо большое!
